FROM php:8.1-fpm-buster
RUN docker-php-ext-install mysqli pdo pdo_mysql memcached
RUN touch /usr/local/etc/php/conf.d/date.ini && echo "date.timezone = Europe/Paris" >> /usr/local/etc/php/conf.d/date.ini
