FROM php:8.1-fpm-buster
RUN apt update && apt -y install zlib1g-dev libmemcached-dev libmemcached11 && printf "\n" | pecl install memcached && docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable memcached
RUN touch /usr/local/etc/php/conf.d/date.ini && echo "date.timezone = Europe/Paris" >> /usr/local/etc/php/conf.d/date.ini
